
# Set the version
version: '3'

# Create a newtork under the name of "inception"
networks:
    inception:
        name: inception
        driver: bridge

# Create Volumes
volumes:
    mariadb:
        driver_opts:
            type: none
            o: bind
            device: /home/amaitou/mariadb/
        name: mariadb
    
    wordpress:
        driver_opts:
            type: none
            o: bind
            device: /home/amaitou/wordpress/
        name: wordpress

# Define services (nginx, worpdress, mariadb)
services:
    # nginx
    nginx:
        expose:
            - "443"
        container_name: nginx
        image: nginx:1337
        build:
            context: ./requirements/nginx/.
        stdin_open: true
        tty: true
        ports:
            - "443:443"
        restart: always
        networks:
            - inception
        depends_on:
            - wordpress
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html/wordpress

    # mariadb
    mariadb:
        expose:
            - "3306"
        container_name: mariadb
        image: mariadb:1337
        stdin_open: true
        tty: true
        ports:
            - "3306:3306"
        restart: always
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        build:
            context: ./requirements/mariadb/.
    
    # wordpress
    wordpress:
        expose:
            - "9000"
        container_name: wordpress
        image: wordpress:1337
        stdin_open: true
        tty: true
        ports:
            - "9000:9000"
        networks:
            - inception
        env_file:
            - .env
        volumes:
            - wordpress:/var/www/html/wordpress
        build:
            context: ./requirements/wordpress/.
        depends_on:
            - mariadb
